blank_issues_enabled: false       # ← hides the "Open blank issue" option
contact_links:
  - name: Question / Help / Discussion
    url: https://github.com/bkaewell/cloudflare-verified-ddns/discussions
    about: Please ask usage questions here instead of opening issues
